### ISSUE TITLE
[Feature Request] Dockerfile Implementation

### ISSUE THREAD

**Issue by 0x0D15** [D3vl0per/Valorant-watcher#1]
Would you consider creating a dockerfile for this project so it can be scaled faster/easier. Either way thanks for the great project!

**Comment by D3vl0per** [comment]
Good idea!

**Comment by D3vl0per** [comment]
@Rayqan Can you test the docker build and image on dev branch?

**Comment by D3vl0per** [comment]
I want to be sure, before merge. :smiley:
