### ISSUE TITLE
Save complicated code by using anomaly stream

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [D3vl0per/Valorant-watcher#14]
Anomaly streams 24/7 at https://www.twitch.tv/anomaly. Using this page directly would mean that a lot of complicated code could be scrapped and would make the program less error-prone.

**Comment by D3vl0per** [comment]
'The selection is random to give fairness, but we give a higher ‘weight’ to those of you who have more hours watched of VALORANT streams. This weight gives you a higher chance at being selected but it’s still not guaranteed.'
Source: https://beta.playvalorant.com/en-us/news/announcements/day-1-closed-beta-in-eu-na-and-moving-forward/

**Comment by D3vl0per** [comment]
I just maxed out the environmental variables. :-D

**Comment by D3vl0per** [comment]
I you want write a lightweight version. 🙂

**Comment by D3vl0per** [comment]
Good cooding 🤗!

**Comment by D3vl0per** [comment]
Can I close this issue?
