### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by Nou4r** [D3vl0per/Valorant-watcher#15]
> =========================
� Check config file...  ✅ Json config found
(node:9292) UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (C:\Users\nour\Documents\vw\1337nour\node_modules\puppeteer-core\lib\Launcher.js:236:15)
    at async C:\Users\nour\Documents\vw\1337nour\app.js:43:15
(node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by alanferreiravalorant** [comment]
First: Thank you for this release its very cool

Tutorial for windows

**-You need to download chromium (extract in your computer)

-Open cmd and navigate to folder bot like a this: cd C:\Users\you-username\Downloads\bot
-type npm install
-type npm start
-put your auth-key
-put commanline for exe chromium like a this:
C:\Users\you-username\Downloads\chrome\chrome.exe
Press enter and done.

FIXES:
**If you get error restart the bot (CTRL+C) and "npm start" again in cmd.

**Comment by D3vl0per** [comment]
@Nou4r 
Please tell me your OS, valorant-watcher version.
Did you download the chromium browser?

**Comment by spheppner** [comment]
Btw for the people who dont know how to access the twitch auth token:
Chrome: F12->Application->Cookies and under twitch.tv there should be an entry for auth token
Obviously you need to do this on the twitch website

**Comment by corediggr** [comment]
thank you for the neat script and help.

i´m using windows 10 and downloaded and installed all the programs.

i used the steps provided by alanferreiravalorant  and program seems to work (see pic).

is it right that only the cmd window shows up (or should it also auto start chromium?)

and is docker really needed then?

thx 4 help :)

![watchR - Kopie](https://user-images.githubusercontent.com/64073257/79853060-dac07d00-83c7-11ea-9adb-19f3bb77dcb0.png)

**Comment by D3vl0per** [comment]
@Nou4r Are solved this problem?
