### ISSUE TITLE
Windows 10 issue with Chromium 

### ISSUE THREAD

**Issue by FinnKliewer** [D3vl0per/Valorant-watcher#16]
� Check config file...  ✅ Json config found
(node:2840) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:\Users\Finn Kliewer\AppData\Local\Chromium\Application ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\Finn Kliewer\node_modules\puppeteer-core\lib\Launcher.js:615:20)
    at ChildProcess.<anonymous> (C:\Users\Finn Kliewer\node_modules\puppeteer-core\lib\Launcher.js:607:71)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My Chromium is executable is at C:\Users\USERNAME\AppData\Local\Chromium\Application which seems odd as I would expect it to be installed to C:\Program Files(x86)\Google\Chromium\ or somewhere within my program files however I reinstalled Chromium just to make sure and it was still there.

**Comment by alanferreiravalorant** [comment]
First: Thank you for this release its very cool

Tutorial for windows

**-You need to download chromium (extract in your computer)

-Open cmd and navigate to folder bot like a this: cd C:\Users\you-username\Downloads\bot
-type npm install
-type npm start
-put your auth-key
-put commanline for exe chromium like a this:
C:\Users\you-username\Downloads\chrome\chrome.exe
Press enter and done.

FIXES:
**If you get error restart the bot (CTRL+C) and "npm start" again in cmd.

**Comment by D3vl0per** [comment]
I saw this error in this issue: https://github.com/puppeteer/puppeteer/issues/5412
I will investigate it.

**Comment by D3vl0per** [comment]
@OX-S extension also needed. Example: chromium.exe

**Comment by khatibomar** [comment]
the problem you forget to put chrome.exe in the end of the path :)

**Comment by D3vl0per** [comment]
No response, so I will close this issue.
