### ISSUE TITLE
Customizable navigation timeout

### ISSUE THREAD

**Issue by giovanni-orciuolo** [D3vl0per/Valorant-watcher#19]
Sometimes I get a navigation timeout after 30 seconds from Puppeteer while navigating to the Twitch streamer page. It would be nice if I could customize this countdown from docker env directly, or a config of some sorts. I can make a PR about this if you wish

**Comment by giovanni-orciuolo** [comment]
Just made the PR 🌟

**Comment by D3vl0per** [comment]
Soory, i don’t understand. 😕

**Comment by giovanni-orciuolo** [comment]
I made a Pull Request to request you to merge my changes into your main repo. I added a navigation timeout

**Comment by giovanni-orciuolo** [comment]
#21

**Comment by D3vl0per** [comment]
Good job!
https://github.com/D3vl0per/Valorant-watcher/tree/2.0.1

**Comment by giovanni-orciuolo** [comment]
Could you update the docker image?

**Comment by D3vl0per** [comment]
I did it!
![Screenshot_20200418_001302](https://user-images.githubusercontent.com/34040149/79618081-6658b600-8109-11ea-8ccf-51ebc5eb6956.png)

**Comment by parentless** [comment]
I have that version with the customizeable timeouts and that error is still happening for me?

**Comment by realjesset** [comment]
> I have that version with the customizeable timeouts and that error is still happening for me?

likewise, I have tried to add timeouts and stuff yet it hasn't been solving the issue.
