### ISSUE TITLE
Offline Error

### ISSUE THREAD

**Issue by 0x1-1** [D3vl0per/Valorant-watcher#26]
Hello, i runned this script on W10. 

But everytime getting offline. When i check on chrome typing link.  I seen the streamer is online. How is that possible? 
![image](https://user-images.githubusercontent.com/35432275/79641569-03b2f900-81a1-11ea-9c18-c34a8093b092.png)

**Comment by D3vl0per** [comment]
@DoubleHub This is your account status.
