### ISSUE TITLE
Undefined streamer

### ISSUE THREAD

**Issue by Peredery** [D3vl0per/Valorant-watcher#27]
Sometimes I got

valorant-watcher_1 | 🔗 Streamer: **https://www.twitch.tv/undefined**
valorant-watcher_1 | 💡 Status: Online
valorant-watcher_1 | 💤 Watching for 8 minutes

**Comment by D3vl0per** [comment]
Yep, the getAllStreamer function is broken.
I working on the next release.

**Comment by D3vl0per** [comment]
Old: `let watch = streamers[getRandomInt(0, streamers.length)];`
New: `let watch = streamers[getRandomInt(0, streamers.length-1)];`
