### ISSUE TITLE
Run multiple account

### ISSUE THREAD

**Issue by arturitosanchez** [D3vl0per/Valorant-watcher#29]
Hi Can i run multiple accounts on windows? How i can do it?

**Comment by D3vl0per** [comment]
Maybe proxy.

**Comment by arturitosanchez** [comment]
How to do it add another proxy to another instances?

**Comment by D3vl0per** [comment]
You need to use docker or create multiple folder

**Comment by arturitosanchez** [comment]
i will do it on windows so i need to duplicate just valorant watcher and use same chrome yes?
