### ISSUE TITLE
It works on macOS 

### ISSUE THREAD

**Issue by OMKE** [D3vl0per/Valorant-watcher#30]
So it works on macOS too.
It gives an error when tried to run with regular chrome so I installed Chromium with 
`brew cask install chromium`
Then simply navigate to executable.
/Applications/Chromium.app/Contents/MacOS/Chromium

https://www.loom.com/share/fd234e2681fc49c1967c8e312146d44c

**Comment by D3vl0per** [comment]
@OMKE I may have a request? Can you make a how-to install video on MacOS, because I'll show at the readme.

**Comment by OMKE** [comment]
Ok, so it's pretty straightforward and doesn't really need a video 😄.
You can download chromium from 
https://download-chromium.appspot.com/, extract and from folder chrome-mac move Chromium.app to the Applications folder.

Or with brew: 
`brew cask install chromium`

When it asks for chromium executable type: 
`/Applications/Chromium.app/Contents/MacOS/Chromium`

**Comment by D3vl0per** [comment]
@OMKE Ok for you, but please filter out README tag at issue section :smile: .

**Comment by OMKE** [comment]
Apparently I can't do that, but I got the key man, thanks very much

**Comment by D3vl0per** [comment]
@OMKE Please join to our new discord server: https://discord.gg/s8AH4aZ
