### ISSUE TITLE
Hang during user menu click

### ISSUE THREAD

**Issue by jvogit** [D3vl0per/Valorant-watcher#32]
I'm running on Google cloud instance on Debian 9.

Every so often I believe Puppeteer hangs on when trying to click for the user sidebar [here](https://github.com/D3vl0per/Valorant-watcher/blob/22aa6019f0491e60484b4647e7ac0e019cdd709c/app.js#L193) from what I can debug. I don't think the problems stems necessarily from this library, but I am letting you know.

I removed this portion as I don't think it will affect the overall purpose. Let me know if this is okay, and I will update if I have received a drop or not.

**Comment by D3vl0per** [comment]
It just a status check for your twitch status.
