### ISSUE TITLE
Im a fucking dumbass

### ISSUE THREAD

**Issue by atnarb** [D3vl0per/Valorant-watcher#34]
how do I open it, I just want a key I know nothing about programming I've downloaded everything and I've tried opening every file, app.js is probably the one I'm supposed to open but it gives me an error message. Line 2 Char 1 and the source is Microsoft JScript compilation error. I know nothing about code can someone walk me through it? I'm also on windows, so.

**Comment by D3vl0per** [comment]
Please send screenshot about error!

**Comment by atnarb** [comment]
![error](https://user-images.githubusercontent.com/56791945/79867508-4dfbcc00-8393-11ea-8008-a697fc17fcca.png)

**Comment by D3vl0per** [comment]
You just click on app.js in zip?

**Comment by atnarb** [comment]
yes

**Comment by atnarb** [comment]
oh shit i should extract it shouldn't i?

**Comment by D3vl0per** [comment]
Okay, please read the README file. Thanks!

**Comment by giovanni-orciuolo** [comment]
Wow

**Comment by D3vl0per** [comment]
> Wow
:smile:

**Comment by D3vl0per** [comment]
@AfkBranta Are you solved this problem?
