### ISSUE TITLE
How to use proxy with password?

### ISSUE THREAD

**Issue by sonbezsna** [D3vl0per/Valorant-watcher#35]
Have proxy like this format
92.120.165.244:57057:USERNAME:PASSWORD
Please help

**Comment by D3vl0per** [comment]
You need to set an extra header:

```javascript
await page.setExtraHTTPHeaders({
    ‘Proxy-Authorization’: ‘Basic ‘ + Buffer.from(‘user:pass’).toString(‘base64’)
})
```

**Comment by sonbezsna** [comment]
Where to add this ? And how to use?

**Comment by sonbezsna** [comment]
Ah, nevermind, i'm not a coder but seems found better solution 

// await page.authenticate({ username, password });
