### ISSUE TITLE
Program stops working after the fourth watcher

### ISSUE THREAD

**Issue by Ceereals** [D3vl0per/Valorant-watcher#36]
Hi, I have been using "the bot" for a few hours now and I noticed that after the fourth watcher the program crashes without showing any type of error on the screen, it is as if it were stuck, the only way to run it was by pressing CTRL + C since I am on windows, without closing the process.

**Comment by D3vl0per** [comment]
Please send a screenshot!

**Comment by octopusknives** [comment]
I am on windows and I can't reproduce this

**Comment by Ceereals** [comment]
> 
> 
> Please send a screenshot!

Where I traced the line the program had stopped and started again via CTRL + C. I added a time indicator to understand if the bot is respecting the display time on each streamer.
In addition from the screenshots I noticed that the video player does not work and from an error # 1000, the drops still work?
![Screenshot](https://user-images.githubusercontent.com/26823400/79954279-69430600-847d-11ea-82ba-30f7f13a70aa.png)

**Comment by Ceereals** [comment]
I think the problem is:
https://github.com/D3vl0per/Valorant-watcher/blob/22aa6019f0491e60484b4647e7ac0e019cdd709c/app.js#L179

Probably in some pages the button for mature content is not shown and freezes because of the await, and pressing CTRL + C forces the resolution of the Promise.

**Comment by AmusingThrone** [comment]
This issue still exists, I have a PR for it and will send it soon.
