### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by theunrealmachine** [D3vl0per/Valorant-watcher#37]
This happened after >15 hour run. Seems like the bot freezed too. I was running it using Docker.

```
valorant-watcher_1  | 🔗 Streamer:  https://www.twitch.tv/72hrs
valorant-watcher_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
valorant-watcher_1  |     at viewRandomPage (/usr/src/app/app.js:195:58)
valorant-watcher_1  |     at runMicrotasks (<anonymous>)
valorant-watcher_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
valorant-watcher_1  |     at async main (/usr/src/app/app.js:78:5)
valorant-watcher_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eith
er by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .c
atch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (s
ee https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
valorant-watcher_1  | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future,
 promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sonbezsna** [comment]
Same error with cmd, running for 30 min and get this. After restart still getting error.
> 
> � Streamer:  https://www.twitch.tv/mickiepp
> (node:18800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
>     at viewRandomPage (C:\Users\Computer\Desktop\twitch\app.js:200:58)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async main (C:\Users\Computer\Desktop\twitch\app.js:83:5)
> (node:18800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:18800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Krixx1337** [comment]
Same here: https://i.imgur.com/vzuCpov.png

**Comment by D3vl0per** [comment]
Try to remove status detection: https://github.com/D3vl0per/Valorant-watcher/blob/22aa6019f0491e60484b4647e7ac0e019cdd709c/app.js#L195

**Comment by sonbezsna** [comment]
Works now

> Try to remove status detection:
> 
> https://github.com/D3vl0per/Valorant-watcher/blob/22aa6019f0491e60484b4647e7ac0e019cdd709c/app.js#L195
