### ISSUE TITLE
Quality configuration suggestion

### ISSUE THREAD

**Issue by theunrealmachine** [D3vl0per/Valorant-watcher#38]
I think it would be useful to add the possibility to reduce stream quality. I was running the bot for a little bit more than 15 hours on my VPS, and it has used up ~15 GB of bandwidth. Not too much, but still.
And thanks for your work anyway!

**Comment by 0xAhmet** [comment]
Yes it would be nice. Im running 6 bots and my bandwidth usage is very high. 

I wish there was an option to select lowest quality possible. 
![chrome_4ATEqkBU1g](https://user-images.githubusercontent.com/11314042/79872267-40276480-83ee-11ea-8bdf-2849d55c7c91.png)

**Comment by D3vl0per** [comment]
Nice farming :smile: .
I'll try to find a solution how to switch stream quality.

**Comment by rvkolosov** [comment]
> Nice farming 😄 .
> I'll try to find a solution how to switch stream quality.

What you think about this suggestion?

```await driver.executeScript(`window.localStorage.setItem('video-quality','{"default":"160p30"}')`)```
