### ISSUE TITLE
"The broadcaster has indicated that this channel is intended for mature audiences."

### ISSUE THREAD

**Issue by hexiro** [D3vl0per/Valorant-watcher#5]
The bot doesn't click the "Start Watching" button and I don't know if this affects drops and needs to be address.

Screenshot: https://i.imgur.com/J2cByz6.jpg

**Comment by D3vl0per** [comment]
Hmm.... Looks strange.
Please share the actual streamer’s link.

**Comment by hexiro** [comment]
how is that strange? all streamers that are deemed as "18+" have that

**Comment by D3vl0per** [comment]
Please attach the actual streamer’s link.

**Comment by heyimrendy** [comment]
> Please attach the actual streamer’s link.

I fixed this by emulates mouse click on this button element whenever element exist on first stream load. Test case https://www.twitch.tv/m0e_tv
`#root > div > div.tw-flex.tw-flex-column.tw-flex-nowrap.tw-full-height > div > main > div.root-scrollable.scrollable-area.scrollable-area--suppress-scroll-x > div.simplebar-scroll-content > div > div > div.persistent-player > div.player-aspect > div.video-player > div > div > div > div.content-overlay-gate.player-overlay-background.player-overlay-background--darkness-0.tw-absolute.tw-align-items-center.tw-bottom-0.tw-c-text-overlay.tw-flex.tw-flex-column.tw-justify-content-center.tw-left-0.tw-right-0.tw-top-0 > div > div.content-overlay-gate__allow-pointers.tw-mg-t-3 > button`

**Comment by D3vl0per** [comment]
Thanks for help @heyimrendy ! I will write a jquery to detect this button!

**Comment by D3vl0per** [comment]
New version release!
Please try it.
