### ISSUE TITLE
README open the bot easily on windows

### ISSUE THREAD

**Issue by louanfontenele** [D3vl0per/Valorant-watcher#53]
To execute the bot easily, create a **.bat** file and put this code, save and execute
```bat
@echo off
Pushd "C:\Valorant-watcher-master"
node app
```
Change `C:\Valorant-watcher-master` to your bot location

**Comment by D3vl0per** [comment]
Somebody please test this!

**Comment by SuperSandro2000** [comment]
This only works if you downloaded and extracted the zip to ``C:\Valorant-watcher-master``. If you need to adjust the path of Pushd you can also tell users to open a console in the cloned/extracted directory and run ``node app``.

**Comment by SuperSandro2000** [comment]
Also ``Pushd`` is Powershell and not cmd which is the windows default shell to run ``.bat``.

**Comment by louanfontenele** [comment]
> This only works if you downloaded and extracted the zip to `C:\Valorant-watcher-master`. If you need to adjust the path of Pushd you can also tell users to open a console in the cloned/extracted directory and run `node app`.

> Also `Pushd` is Powershell and not cmd which is the windows default shell to run `.bat`.


It's work for any drive, and you just need to change the location. and Yes Pushd is works in CMD too. :D i'm using at this moment, and my video can prove it. You can see it: https://youtu.be/BvCUnhw9Vcw?t=404

**Comment by SuperSandro2000** [comment]
> you just need to change the location.

Which makes this not to useful.

> Pushd is works in CMD too.

Maybe I did a typo but you are right. We could also use ``cd`` which is more commonly known.

I believe you that it works for you but it is not really useful cause you can just open a command line and type in ``node app``.

Also if this crashes the command line just closes and you see no error.

**Comment by louanfontenele** [comment]
> Which makes this not to useful.

Of course is useful, because you don't need to put the command all the time.

> I believe you that it works for you but it is not really useful cause you can just open a command line and type in `node app`.

just change to npm start, as i show in the command on top of this thread.

> Also if this crashes the command line just closes and you see no error.

use as i showed, and test with `npm start` or `node app`

**Comment by SuperSandro2000** [comment]
> Of course is useful, because you don't need to put the command all the time.

This script sniped would be useful in the root.

```
@echo off
npm start
```
