### ISSUE TITLE
Stuck it "Now watching streamer"

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [D3vl0per/Valorant-watcher#57]
Hey,
I am running it from Docker and I think it got stuck for 2 hours. I have the timestamp on the image. The current time is 3:16 and it got stuck at 1:00.
Thanks,
Miguel de Carvalho

![](https://i.imgur.com/Q4koFh0.jpg)

**Comment by D3vl0per** [comment]
Please insert [here](https://github.com/D3vl0per/Valorant-watcher/blob/a0e2a023c0809764aa8da056f273ff1e9594b000/app.js#L89) this:` await page.waitFor(5000);` // or bigger delay

**Comment by MiguelNdeCarvalho** [comment]
So basically docker image isn't updated right? Thanks for the fast response mate

**Comment by D3vl0per** [comment]
If the stream not loading as fast as the code click it , the whole function stop at watching without any interaction. 
The main problem the network connection. :-|

**Comment by MiguelNdeCarvalho** [comment]
Basically my network sucks 😰. Thanks again, keep good work bro.

**Comment by D3vl0per** [comment]
Thanks! Please close issue. :smiley: 
Happy Drop hunting!
