### ISSUE TITLE
UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by ZaharyMomchilov** [D3vl0per/Valorant-watcher#6]
Checking login...  (node:712401) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/zahary/Documents/ValorantWatcher/Valorant-watcher/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/home/zahary/Documents/ValorantWatcher/Valorant-watcher/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/zahary/Documents/ValorantWatcher/Valorant-watcher/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/home/zahary/Documents/ValorantWatcher/Valorant-watcher/node_modules/puppeteer/lib/helper.js:112:23)
    at checkLogin (/home/zahary/Documents/ValorantWatcher/Valorant-watcher/app.js:163:16)
    at /home/zahary/Documents/ValorantWatcher/Valorant-watcher/app.js:38:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:712401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:712401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tomocrafter** [comment]
I also got this problem, and real problem is node doesn't exit process correctly after this error and just be suspended. So I'm running this program on docker-compose with setting `restart: always` but program never exit therefore it never restarts.

**Comment by ZaharyMomchilov** [comment]
I fixed it by starting node with this argument "--unandled-rejections=none"

**Comment by Coelhomatias** [comment]
> I fixed it by starting node with this argument "--unandled-rejections=none"

sry to bother but exactly what command did you run? is it `npm start --unhandled-rejections=none` ?

**Comment by D3vl0per** [comment]
#19
