### ISSUE TITLE
add instruction for autostart linux

### ISSUE THREAD

**Issue by yohudood** [D3vl0per/Valorant-watcher#63]
i need help white the setup to make it autostart on linux

**Comment by SuperSandro2000** [comment]
If you use the docker-compose version it should do this by itself.

**Comment by yohudood** [comment]
thanks for the tip but my rpi (2b 516) he can barely turn it without docker

**Comment by D3vl0per** [comment]
https://lmgtfy.com/?q=nodejs+autostart+linux
