### ISSUE TITLE
watching an offline stream

### ISSUE THREAD

**Issue by allanf181** [D3vl0per/Valorant-watcher#65]
I went to check the screenshot folder to find out how the bot was doing and found a print of an offline stream, was it supposed to happen?
![vitacelestine_](https://user-images.githubusercontent.com/14101716/81455480-b7d2ee80-9165-11ea-907c-ffdd0763ad4e.png)
```
? Now watching streamer:  https://www.twitch.tv/vitacelestine_
? Screenshot created: vitacelestine_.png
? Account status: assistindo à transmissão de threezin do jogo VALORANT
? Time: 19:24:01
? Watching stream for 25 minutes
```

**Comment by SuperSandro2000** [comment]
Maybe she went offline in the 25 minutes?

**Comment by allanf181** [comment]
a screenshot is taken when the page loads, so it was already offline

**Comment by D3vl0per** [comment]
It is a coincidence.
Adjust your refresh time.
