### ISSUE TITLE
Where can I find the expire date?

### ISSUE THREAD

**Issue by Jan710** [D3vl0per/Valorant-watcher#7]
![Screenshot 2020-04-15 at 16 52 05](https://user-images.githubusercontent.com/46608056/79351955-905b7e00-7f39-11ea-85eb-13ad0c4c7b37.png)

is this the expire date?

**Comment by D3vl0per** [comment]
Yes, but this format is different. Please copy-paste the date from readme(How token does it look like section) and modify it. The date is not as importan as auth-token.D3v---- On Sze, 15 ápr. 2020 16:53:37 +0200  Jan710<notifications@github.com> wrote ---- 
 
is this the expire date?

**Comment by Jan710** [comment]
Thanks for the fast reply, so they are valid until 2030? Now Im getting a new error, that the browser isnt supported. 
<img width="698" alt="Screenshot 2020-04-15 at 18 41 19" src="https://user-images.githubusercontent.com/46608056/79363937-df5cdf80-7f48-11ea-89f1-41f723eadded.png">

**Comment by D3vl0per** [comment]
Puppeteer just watching the site, it’s not compatibile with HSL.

**Comment by Jan710** [comment]
Alright, but then you cant get a key? I thought you need to watch and even need to have sound activated.

**Comment by D3vl0per** [comment]
I redirect this problem to a new issue: #9 
WIP to correct this problem ASAP.
