### ISSUE TITLE
[WIP] New auto browser framework

### ISSUE THREAD

**Issue by D3vl0per** [D3vl0per/Valorant-watcher#9]
Video playback does not work with puppeteer so I want to replace it...

**Comment by D3vl0per** [comment]
New release is cooming...
Picture from puppeter:
![actual-steamer](https://user-images.githubusercontent.com/34040149/79466891-76836f00-7ffd-11ea-8ee6-0efa55efa96d.png)

**Comment by SScorpyo** [comment]
is this done?

**Comment by D3vl0per** [comment]
@Scorpyooooo #13
